addSbtPlugin("com.lucidchart"     % "sbt-scalafmt" % "1.15")
addSbtPlugin("com.github.sbt"  % "sbt-release"  % "1.0.15")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype" % "3.9.5")
addSbtPlugin("com.github.sbt"       % "sbt-pgp"      % "2.1.2")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.10")
