name: Website
on:
  push:
    branches: [master]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
      - uses: sbt/setup-sbt@v1
      - uses: olafurpg/setup-gpg@v3
      - run: sbt '++2.13.15; docs/docusaurusPublishGhpages'
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
      - name: Check git diff
        if: ${{ failure() }}
        run: git diff
